
---
queue_rules:
  - name: default
    conditions:
      - check-success=ci

pull_request_rules:
  - name: Auto-Merge on Label
    actions:
      queue:
        method: rebase
        rebase_fallback: null
        name: default
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
  - name: Auto-Merge Green Backports
    actions:
      queue:
        method: rebase
        rebase_fallback: null
        name: default
    conditions:
      - label!=conflicts
      - head~=mergify/bp
  - name: backport 2.13
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.13'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.13
  - name: backport 2.12
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.12'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.12
  - name: backport 2.11
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.11'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.11
  - name: backport 2.10
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.10'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.10
  - name: backport 2.9
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.9'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.9
  - name: backport 2.8
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.8'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.8
  - name: backport 2.7
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.7'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.7
  - name: backport 2.6
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.6'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.6
  - name: backport 2.5
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.5'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.5
  - name: backport 2.4
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.4'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.4
  - name: backport 2.3
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.3'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.3
  - name: backport 2.2
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.2'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.2
  - name: backport 2.1
    actions:
      backport:
        ignore_conflicts: true
        branches:
          - 'release-2.1'
        assignees:
          - '{{author}}'
    conditions:
      - merged
      - label=release-2.1
