kind: Deployment
apiVersion: v1
metadata:
  displayName: "Top Speed Windowing"
  name: top-speed-windowing
  namespace: default
spec:
  deploymentTargetName: vvp-jobs
  template:
    spec:
      parallelism: 1
      artifact:
        kind: JAR
        flinkVersion: '1.12'
        jarUri: >-
          https://repo1.maven.org/maven2/org/apache/flink/flink-examples-streaming_2.12/1.12.0/flink-examples-streaming_2.12-1.12.0-TopSpeedWindowing.jar

